language: ruby
rvm:
  - 2.0.0
env:
  - DB=postgresql
script:
  - RAILS_ENV=test POLTERGEIST=true bundle exec rake --trace db:migrate spec
before_script:
  - psql -c 'create database opensit_test' -U postgres
cache:
  bundler: true
  directories:
    - tmp/cache/assets/test/sprockets
